default:
  before_script:
    - 'apk update'
    - 'apk upgrade'
    - 'apk add git nodejs-current npm shellcheck'
    - 'npm install --global yarn'
    - 'yarn install --frozen-lockfile'

  image: 'alpine:latest'

lint:
  script:
    - 'yarn run lint'

  stage: 'lint'

stages:
  - 'lint'
  - 'test'

test:
  artifacts:
    reports:
      cobertura: 'tmp/test/reports/coverage/cobertura-coverage.xml'
      junit: 'tmp/test/reports/unit/junit.xml'

    when: 'always'

  coverage: '/All files.*\s+(\d+)\s+\|.*$/'

  script:
    - 'yarn run test --ci'

  stage: 'test'
