default:
  before_script:
    - 'apk update'
    - 'apk upgrade'
    - 'apk add git nodejs-current npm shellcheck'
    - 'npm install --global yarn'
    - 'yarn install --frozen-lockfile'

  image: 'alpine:latest'

lint:
  script:
    - 'yarn run lint'

  stage: 'lint'

stages:
  - 'lint'
  - 'test'

test:
  coverage: '/All files.*\s+(\d+)\s+\|.*$/'

  script:
    - 'yarn run test --ci'

  stage: 'test'
