default:
  before_script:
    - 'env'
    - 'yarn install --cache-folder .yarn-cache --frozen-lockfile --prefer-offline'

  cache:
    key:
      files:
        - 'yarn.lock'

    paths:
      - '.yarn-cache'
      - 'tmp/lint/schemas'

  image: 'node:latest'

lint:
  needs: []

  script:
    - 'yarn run lint'

  stage: 'lint'

pack:
  artifacts:
    paths:
      - '${CI_PROJECT_PATH_SLUG}-git-${CI_COMMIT_SHA}.tgz'

  needs: []

  script:
    - 'yarn pack --filename "${CI_PROJECT_PATH_SLUG}-git-${CI_COMMIT_SHA}.tgz"'

  stage: 'pack'

release:
  only:
    - 'alpha'
    - 'beta'
    - 'master'
    - 'next'
    - 'next-major'

  script:
    - 'echo "unsafe-perm = true" >> .npmrc'
    - 'yarn run semantic-release --repository-url "${CI_REPOSITORY_URL}"'

  stage: 'release'

stages:
  - 'lint'
  - 'test'
  - 'pack'
  - 'release'

test:
  artifacts:
    reports:
      cobertura: 'tmp/test/reports/coverage/cobertura-coverage.xml'
      junit: 'tmp/test/reports/unit/junit.xml'

    when: 'always'

  coverage: '/All files.*\s+(\d+)\s+\|.*$/'

  needs: []

  script:
    - 'yarn run test --ci'

  stage: 'test'
