default:
  before_script:
    - 'yarn install --cache-folder .yarn-cache --frozen-lockfile --prefer-offline'

  cache:
    key:
      files:
        - 'yarn.lock'

    paths:
      - '.yarn-cache'

  image: 'node:latest'

lint:
  script:
    - 'yarn run lint'

  stage: 'lint'

pack:
  artifacts:
    paths:
      - 'schroedernet-commitlint-config-git-${CI_COMMIT_SHA}.tgz'

  script:
    - 'yarn pack --filename "schroedernet-commitlint-config-git-${CI_COMMIT_SHA}.tgz"'

  stage: 'pack'

stages:
  - 'lint'
  - 'test'
  - 'pack'

test:
  artifacts:
    reports:
      cobertura: 'tmp/test/reports/coverage/cobertura-coverage.xml'
      junit: 'tmp/test/reports/unit/junit.xml'

    when: 'always'

  coverage: '/All files.*\s+(\d+)\s+\|.*$/'

  script:
    - 'yarn run test --ci'

  stage: 'test'
