default:
  before_script:
    - 'yarn install --cache-folder .yarn-cache --frozen-lockfile --prefer-offline'

  cache:
    key:
      files:
        - 'yarn.lock'

    paths:
      - '.yarn-cache'
      - 'tmp/lint/schemas'

  image: 'node:latest'

lint:
  except:
    - 'schedules'

  needs: []

  script:
    - 'yarn run lint'

  stage: 'lint'

mirror:
  before_script: []
  cache: {}

  only:
    refs:
      - 'schedules'
    variables:
      - '$CANONICAL_PROJECT_URL'
      - '$MIRROR_USER'
      - '$MIRROR_TOKEN'

  script:
    - 'cd /tmp'
    - 'git clone "${CANONICAL_PROJECT_URL}.git"'
    - 'cd "${CI_PROJECT_NAME}"'
    - 'git remote add mirror "https://${MIRROR_USER}:${MIRROR_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"'
    - 'git fetch --all'
    - 'git push --all mirror'
    - 'git push --tags mirror'

  stage: 'mirror'

pack:
  artifacts:
    paths:
      - '${CI_PROJECT_PATH_SLUG}-git-${CI_COMMIT_SHA}.tgz'

  except:
    - 'schedules'

  needs: []

  script:
    - 'yarn pack --filename "${CI_PROJECT_PATH_SLUG}-git-${CI_COMMIT_SHA}.tgz"'

  stage: 'pack'

release:
  except:
    - 'schedules'

  only:
    - 'alpha'
    - 'beta'
    - 'master'
    - 'next'
    - 'next-major'

  script:
    - 'echo "unsafe-perm = true" >> .npmrc'
    - 'yarn run semantic-release --repository-url "${CI_REPOSITORY_URL}"'

  stage: 'release'

stages:
  - 'lint'
  - 'test'
  - 'pack'
  - 'release'
  - 'mirror'

test:
  artifacts:
    reports:
      cobertura: 'tmp/test/reports/coverage/cobertura-coverage.xml'
      junit: 'tmp/test/reports/unit/junit.xml'

    when: 'always'

  coverage: '/All files.*\s+(\d+)\s+\|.*$/'

  except:
    - 'schedules'

  needs: []

  script:
    - 'yarn run test --ci'

  stage: 'test'
