import {RulesConfig} from '@commitlint/types'

export const rules: RulesConfig = {
  'body-case':              [2, 'always', 'sentence-case'                     ],
  'body-empty':             [0                                                ],
  'body-leading-blank':     [2, 'always'                                      ],
  'body-max-length':        [2, 'always', Infinity                            ],
  'body-max-line-length':   [2, 'always', 72                                  ],
  'body-min-length':        [2, 'always', 0                                   ],
  'footer-empty':           [0                                                ],
  'footer-leading-blank':   [2, 'always'                                      ],
  'footer-max-length':      [2, 'always', Infinity                            ],
  'footer-max-line-length': [2, 'always', 72                                  ],
  'footer-min-length':      [2, 'always', 0                                   ],
  'header-case':            [0                                                ],
  'header-full-stop':       [2, 'never'                                       ],
  'header-max-length':      [2, 'always', 72                                  ],
  'header-min-length':      [2, 'always', 0                                   ],
  'references-empty':       [0                                                ],
  'scope-case':             [2, 'always', 'lower-case'                        ],
  'scope-empty':            [2, 'never'                                       ],
  'scope-enum':             [2, 'always', ['contrib', 'deps', 'gitlab',
                                           'license', 'lint', 'package']      ],
  'scope-max-length':       [2, 'always', Infinity                            ],
  'scope-min-length':       [2, 'always', 0                                   ],
  'signed-off-by':          [0                                                ],
  'subject-case':           [2, 'always', 'sentence-case'                     ],
  'subject-empty':          [2, 'never'                                       ],
  'subject-full-stop':      [2, 'never'                                       ],
  'subject-max-length':     [2, 'always', 50                                  ],
  'subject-min-length':     [2, 'always', 0                                   ],
  'type-case':              [2, 'always', 'lower-case'                        ],
  'type-empty':             [2, 'never'                                       ],
  'type-enum':              [2, 'always', ['build', 'ci', 'chore', 'docs',
                                           'feat', 'fix', 'perf', 'refactor',
                                           'revert', 'style', 'test']         ],
  'type-max-length':        [2, 'always', Infinity                            ],
  'type-min-length':        [2, 'always', 0                                   ],
}
